/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import Models.BanHang.HoaDon;
import Services.BanHang.BanHangServices;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author os
 */
public class HoaDonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonJPanel
     */
    public HoaDonJPanel() {
        initComponents();
        fillTableHoaDon();
         tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Giá Trị", "Ngày Tạo", "Số Điện Thoại", "Hình thức thanh toán", "Hình thức nhận hàng", "Trạng thái", "Ghi chú"
            }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhoadon = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hóa Đơn");

        tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Giá Trị", "Ngày Tạo", "Số Điện Thoại", "hình thức thanh toán", "Hình thức nhận hàng", "trạng thái", "ghi chú"
            }
        ));
        tbhoadon.setShowGrid(true);
        tbhoadon.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tbhoadon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(565, 565, 565)
                .addComponent(jLabel1)
                .addContainerGap(568, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void fillTableHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tbhoadon.getModel();
        BanHangServices banHangServices = new BanHangServices();
        List<HoaDon> listhd = banHangServices.GetListHD();

        for (HoaDon hd : listhd) {
            model.addRow(new Object[]{
                hd.getMaHD(),
                hd.getManv(),
                hd.getGiatri(),
                hd.getNgaytao(),
                hd.getSdt(),
                hd.getHinhthucTT(),
                hd.getHinhthucNH(),
                hd.getTrangthai(),
                hd.getGhichu()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhoadon;
    // End of variables declaration//GEN-END:variables
}
