/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;


import Models.ThongKe.ThongKeDoanhThuModel;
import Models.ThongKe.ThongKeNhanVienModel;
import Services.ThongKe.ThongKeDoanhThuspDAO;
import Services.ThongKe.ThongKeNhanVienDAO;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author LVQ
 */
public class ThongKeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeJpanel
     */
    public ThongKeJpanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TKDoanhThuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbDoanhThu = new javax.swing.JLabel();
        TKDoanhThuPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbSHD = new javax.swing.JLabel();
        TKDoanhThuPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbSLSP = new javax.swing.JLabel();
        TKDoanhThuPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbTKH = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        ExportExelSP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDTNV = new javax.swing.JTable();
        txtExportExelDoanhThuNV = new javax.swing.JButton();

        TKDoanhThuPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Doanh Thu");

        jlbDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDoanhThu.setText("000");
        jlbDoanhThu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlbDoanhThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TKDoanhThuPanelLayout = new javax.swing.GroupLayout(TKDoanhThuPanel);
        TKDoanhThuPanel.setLayout(TKDoanhThuPanelLayout);
        TKDoanhThuPanelLayout.setHorizontalGroup(
            TKDoanhThuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDoanhThu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
            .addGroup(TKDoanhThuPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TKDoanhThuPanelLayout.setVerticalGroup(
            TKDoanhThuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKDoanhThuPanelLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jlbDoanhThu)
                .addGap(75, 75, 75))
        );

        TKDoanhThuPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Số Hóa Đơn");

        jlbSHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbSHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSHD.setText("000");

        javax.swing.GroupLayout TKDoanhThuPanel1Layout = new javax.swing.GroupLayout(TKDoanhThuPanel1);
        TKDoanhThuPanel1.setLayout(TKDoanhThuPanel1Layout);
        TKDoanhThuPanel1Layout.setHorizontalGroup(
            TKDoanhThuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TKDoanhThuPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        TKDoanhThuPanel1Layout.setVerticalGroup(
            TKDoanhThuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKDoanhThuPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jlbSHD)
                .addGap(74, 74, 74))
        );

        TKDoanhThuPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Số Sản Phẩm");

        jlbSLSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbSLSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSLSP.setText("000");

        javax.swing.GroupLayout TKDoanhThuPanel2Layout = new javax.swing.GroupLayout(TKDoanhThuPanel2);
        TKDoanhThuPanel2.setLayout(TKDoanhThuPanel2Layout);
        TKDoanhThuPanel2Layout.setHorizontalGroup(
            TKDoanhThuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSLSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TKDoanhThuPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        TKDoanhThuPanel2Layout.setVerticalGroup(
            TKDoanhThuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKDoanhThuPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jlbSLSP)
                .addGap(69, 69, 69))
        );

        TKDoanhThuPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tổng Khách");

        jlbTKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTKH.setText("000");

        javax.swing.GroupLayout TKDoanhThuPanel3Layout = new javax.swing.GroupLayout(TKDoanhThuPanel3);
        TKDoanhThuPanel3.setLayout(TKDoanhThuPanel3Layout);
        TKDoanhThuPanel3Layout.setHorizontalGroup(
            TKDoanhThuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TKDoanhThuPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel4)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        TKDoanhThuPanel3Layout.setVerticalGroup(
            TKDoanhThuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKDoanhThuPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jlbTKH)
                .addGap(68, 68, 68))
        );

        txtTK.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        txtTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTKKeyReleased(evt);
            }
        });

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số Lượng", "Doanh Thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblThongKe);

        ExportExelSP.setText("Xuất Exel");
        ExportExelSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportExelSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExportExelSP)
                .addGap(199, 199, 199))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExportExelSP)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Doanh Thu Sản Phẩm", jPanel2);

        tblDTNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "SL Hóa Đơn", "Tổng Doanh Thu"
            }
        ));
        jScrollPane2.setViewportView(tblDTNV);

        txtExportExelDoanhThuNV.setText("Xuất Exel");
        txtExportExelDoanhThuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExportExelDoanhThuNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtExportExelDoanhThuNV)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExportExelDoanhThuNV)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Doanh thu nhân viên", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TKDoanhThuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TKDoanhThuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(TKDoanhThuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(TKDoanhThuPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(txtTK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TKDoanhThuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TKDoanhThuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TKDoanhThuPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TKDoanhThuPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblThongKe.getModel();
        TableRowSorter<DefaultTableModel> ab = new TableRowSorter<>(dtm);
        tblThongKe.setRowSorter(ab);
        ab.setRowFilter(RowFilter.regexFilter(txtTK.getText(), 0, 1));
    }//GEN-LAST:event_txtTKKeyReleased

    private void ExportExelSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportExelSPActionPerformed
        try {
            URL url = ThongKeJpanel.class.getResource("");
            JFileChooser jfc = new JFileChooser(url.getFile());
            jfc.showDialog(this, "Mời ông cháu chọn file");
            File saveFile = jfc.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet spreadsheet = workbook.createSheet("Danh Sách Sản Phẩm");
                XSSFRow row = null;
                Cell cell = null;
                row = spreadsheet.createRow((short) 0);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("STT");
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Mã SP");
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Tên SP");              
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("Tổng sl sản phẩm");
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("Doanh Thu");
                for (int i = 0; i < tblThongKe.getRowCount(); i++) {
                    row = spreadsheet.createRow((short) 1 + i);
                    row.setHeight((short) 400);
                    row.createCell(0).setCellValue(i + 1);
                    row.createCell(1).setCellValue(tblThongKe.getValueAt(i, 0).toString());
                    row.createCell(2).setCellValue(tblThongKe.getValueAt(i, 1).toString());
                    row.createCell(3).setCellValue(tblThongKe.getValueAt(i, 2).toString());
                    row.createCell(4).setCellValue(tblThongKe.getValueAt(i, 3).toString());
                }
                FileOutputStream out = new FileOutputStream(saveFile);
                JOptionPane.showMessageDialog(this,"Lưu thành công");
                workbook.write(out);
                out.close();
                Desktop.getDesktop().open(saveFile);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ExportExelSPActionPerformed

    private void txtExportExelDoanhThuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExportExelDoanhThuNVActionPerformed
               try {
            URL url = ThongKeJpanel.class.getResource("");
            JFileChooser jfc = new JFileChooser(url.getFile());
            jfc.showDialog(this, "Mời ông cháu chọn file");
            File saveFile = jfc.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet spreadsheet = workbook.createSheet("Danh Sách Doanh Thu Nhân Viên");
                XSSFRow row = null;
                Cell cell = null;
                row = spreadsheet.createRow((short) 0);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("STT");
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Mã NV");
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Tên NV");              
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("SL Hóa Đơn");
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("SL Sản Phẩm");
                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue("Tổng Doanh Thu");
                for (int i = 0; i < tblDTNV.getRowCount(); i++) {
                    row = spreadsheet.createRow((short) 1 + i);
                    row.setHeight((short) 400);
                    row.createCell(0).setCellValue(i + 1);
                    row.createCell(1).setCellValue(tblDTNV.getValueAt(i, 0).toString());
                    row.createCell(2).setCellValue(tblDTNV.getValueAt(i, 1).toString());
                    row.createCell(3).setCellValue(tblDTNV.getValueAt(i, 2).toString());
                    row.createCell(4).setCellValue(tblDTNV.getValueAt(i, 3).toString());
                    row.createCell(5).setCellValue(tblDTNV.getValueAt(i, 4).toString());
                    System.out.println(i);
                }
                FileOutputStream out = new FileOutputStream(saveFile);
                JOptionPane.showMessageDialog(this,"Lưu thành công");
                workbook.write(out);
                out.close();
                Desktop.getDesktop().open(saveFile);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtExportExelDoanhThuNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExportExelSP;
    private javax.swing.JPanel TKDoanhThuPanel;
    private javax.swing.JPanel TKDoanhThuPanel1;
    private javax.swing.JPanel TKDoanhThuPanel2;
    private javax.swing.JPanel TKDoanhThuPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbDoanhThu;
    private javax.swing.JLabel jlbSHD;
    private javax.swing.JLabel jlbSLSP;
    private javax.swing.JLabel jlbTKH;
    private javax.swing.JTable tblDTNV;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JButton txtExportExelDoanhThuNV;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
ThongKeDoanhThuspDAO tt = new ThongKeDoanhThuspDAO();

    private void init() {
        jlbDoanhThu.setText(Double.toString(tt.getTongDoanhThu()));
        jlbSHD.setText(Double.toString(tt.getSHD()));
        jlbSLSP.setText(Double.toString(tt.getSLSP()));
        jlbTKH.setText(Double.toString(tt.getTongKH()));
        fillTableTKDT();
        fillTableTKNV();
    }
    ThongKeNhanVienDAO ttnv = new ThongKeNhanVienDAO();

    private void fillTableTKDT() {
        DefaultTableModel dtm = (DefaultTableModel) tblThongKe.getModel();
        dtm.setRowCount(0);
        for (ThongKeDoanhThuModel thongKeDoanhThuModel : tt.getAll()) {
            Object[] row = {thongKeDoanhThuModel.getMaSP(), thongKeDoanhThuModel.getTenSP(), thongKeDoanhThuModel.getTongsoluongsp(), thongKeDoanhThuModel.getDoanhThu()};
            dtm.addRow(row);
        }

    }

    private void fillTableTKNV() {
        DefaultTableModel dtm = (DefaultTableModel) tblDTNV.getModel();
        dtm.setRowCount(0);
        for (ThongKeNhanVienModel thongKeNhanVienModel : ttnv.getAll()) {
            Object[] row = {thongKeNhanVienModel.getMaNV(), thongKeNhanVienModel.getHoTen(), thongKeNhanVienModel.getSoluonghoadon(), thongKeNhanVienModel.getTongdoanhthu()};
            dtm.addRow(row);
        }
    }
}
